project:
  type: website

website:
  title: "Zhaowen Guo"
  favicon: "headshot_guo.jpg"
  google-analytics: 
    tracking-id: "G-J1PPVYDT7J"
    anonymize-ip: true
  search: 
    location: navbar
    type: overlay
  navbar:
  
    left:
      - href: index.qmd
        text: Home
      - href: statistics.qmd
        text: Statistics
      - href: dataviz.qmd
        text: Data Visualization
      - text: Tutorials
        menu: 
          - text: Word Embeddings with R
            href: tutorials/word_embeddings.html
          - text: Visualizing Data with R
            href: tutorials/data_visualization.html
    
    right:
      - text: LinkedIn
        url: "https://www.linkedin.com/in/zhaowen-guo-20535312a/"
        icon: linkedin
      - text: GitHub
        icon: github
        url: "https://github.com/zwguo95"
      - text: Email
        href: mailto:zwguo@uw.edu
        icon: envelope
      - text: Resume
        icon: file-earmark-person
        menu: 
          - text: Resume
            href: resume/resume_guo.pdf
          - text: CV
            href: resume/cv_guo.pdf

format:
  html:
    theme: 
      - mystyle.scss
    mainfont: Merriweather
    fontsize: 18px
    linestretch: 1.7
    page-layout: article
    citations-hover: true
    code-link: true
    code-fold: show
    code-tools: false