project:
  type: website

website:
  title: "Zhaowen Guo"
  favicon: "headshot_guo.jpg"
    
  search: 
    location: navbar
    type: overlay
  navbar:
  
    left:
      - href: index.qmd
        text: Home
      - href: statistics.qmd
        text: Statistics
      - href: dataviz.qmd
        text: Data Visualization
      - text: Tutorials
        menu: 
          - text: Word Embeddings with R
            href: tutorials/word_embeddings.html
          - text: Visualizing Data with R
            href: tutorials/data_visualization.html
    
    right:
      - text: LinkedIn
        url: "https://www.linkedin.com/in/zhaowen-guo-20535312a/"
        icon: linkedin
      - text: GitHub
        icon: github
        url: "https://github.com/zwguo95"
      - text: Email
        url: "zwguo@uw.edu"
        icon: envelope
      - text: Resume
        url: "resume_guo.pdf"
        icon: file-earmark-person

format:
  html:
    theme: sandstone
    css: styles.css
    page-layout: article
    citations-hover: true
    code-link: true
    code-fold: show
    code-tools: false
    code-block-border-left: "#004E4F"